/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquinosIndexRouteImport } from './routes/equinos.index'
import { Route as EquinosNuevoRouteImport } from './routes/equinos.nuevo'
import { Route as EquinosIdRouteImport } from './routes/equinos.$id'
import { Route as EquinosIdEditarRouteImport } from './routes/equinos.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquinosIndexRoute = EquinosIndexRouteImport.update({
  id: '/equinos/',
  path: '/equinos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquinosNuevoRoute = EquinosNuevoRouteImport.update({
  id: '/equinos/nuevo',
  path: '/equinos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const EquinosIdRoute = EquinosIdRouteImport.update({
  id: '/equinos/$id',
  path: '/equinos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EquinosIdEditarRoute = EquinosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => EquinosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/equinos/$id': typeof EquinosIdRouteWithChildren
  '/equinos/nuevo': typeof EquinosNuevoRoute
  '/equinos/': typeof EquinosIndexRoute
  '/equinos/$id/editar': typeof EquinosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/equinos/$id': typeof EquinosIdRouteWithChildren
  '/equinos/nuevo': typeof EquinosNuevoRoute
  '/equinos': typeof EquinosIndexRoute
  '/equinos/$id/editar': typeof EquinosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/equinos/$id': typeof EquinosIdRouteWithChildren
  '/equinos/nuevo': typeof EquinosNuevoRoute
  '/equinos/': typeof EquinosIndexRoute
  '/equinos/$id/editar': typeof EquinosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/health'
    | '/login'
    | '/equinos/$id'
    | '/equinos/nuevo'
    | '/equinos/'
    | '/equinos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/health'
    | '/login'
    | '/equinos/$id'
    | '/equinos/nuevo'
    | '/equinos'
    | '/equinos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/health'
    | '/login'
    | '/equinos/$id'
    | '/equinos/nuevo'
    | '/equinos/'
    | '/equinos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  EquinosIdRoute: typeof EquinosIdRouteWithChildren
  EquinosNuevoRoute: typeof EquinosNuevoRoute
  EquinosIndexRoute: typeof EquinosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equinos/': {
      id: '/equinos/'
      path: '/equinos'
      fullPath: '/equinos/'
      preLoaderRoute: typeof EquinosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equinos/nuevo': {
      id: '/equinos/nuevo'
      path: '/equinos/nuevo'
      fullPath: '/equinos/nuevo'
      preLoaderRoute: typeof EquinosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equinos/$id': {
      id: '/equinos/$id'
      path: '/equinos/$id'
      fullPath: '/equinos/$id'
      preLoaderRoute: typeof EquinosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equinos/$id/editar': {
      id: '/equinos/$id/editar'
      path: '/editar'
      fullPath: '/equinos/$id/editar'
      preLoaderRoute: typeof EquinosIdEditarRouteImport
      parentRoute: typeof EquinosIdRoute
    }
  }
}

interface EquinosIdRouteChildren {
  EquinosIdEditarRoute: typeof EquinosIdEditarRoute
}

const EquinosIdRouteChildren: EquinosIdRouteChildren = {
  EquinosIdEditarRoute: EquinosIdEditarRoute,
}

const EquinosIdRouteWithChildren = EquinosIdRoute._addFileChildren(
  EquinosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  EquinosIdRoute: EquinosIdRouteWithChildren,
  EquinosNuevoRoute: EquinosNuevoRoute,
  EquinosIndexRoute: EquinosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
