/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquinosIndexRouteImport } from './routes/equinos.index'
import { Route as CampeonatosIndexRouteImport } from './routes/campeonatos.index'
import { Route as UsuariosNuevoRouteImport } from './routes/usuarios.nuevo'
import { Route as ParticipacionesIdRouteImport } from './routes/participaciones.$id'
import { Route as EquinosNuevoRouteImport } from './routes/equinos.nuevo'
import { Route as EquinosIdRouteImport } from './routes/equinos.$id'
import { Route as CampeonatosNuevoRouteImport } from './routes/campeonatos.nuevo'
import { Route as CampeonatosIdRouteImport } from './routes/campeonatos.$id'
import { Route as EquinosIdEditarRouteImport } from './routes/equinos.$id.editar'
import { Route as CampeonatosIdEditarRouteImport } from './routes/campeonatos.$id.editar'

const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquinosIndexRoute = EquinosIndexRouteImport.update({
  id: '/equinos/',
  path: '/equinos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosIndexRoute = CampeonatosIndexRouteImport.update({
  id: '/campeonatos/',
  path: '/campeonatos/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosNuevoRoute = UsuariosNuevoRouteImport.update({
  id: '/usuarios/nuevo',
  path: '/usuarios/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipacionesIdRoute = ParticipacionesIdRouteImport.update({
  id: '/participaciones/$id',
  path: '/participaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EquinosNuevoRoute = EquinosNuevoRouteImport.update({
  id: '/equinos/nuevo',
  path: '/equinos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const EquinosIdRoute = EquinosIdRouteImport.update({
  id: '/equinos/$id',
  path: '/equinos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosNuevoRoute = CampeonatosNuevoRouteImport.update({
  id: '/campeonatos/nuevo',
  path: '/campeonatos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosIdRoute = CampeonatosIdRouteImport.update({
  id: '/campeonatos/$id',
  path: '/campeonatos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EquinosIdEditarRoute = EquinosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => EquinosIdRoute,
} as any)
const CampeonatosIdEditarRoute = CampeonatosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => CampeonatosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reportes': typeof ReportesRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/nuevo': typeof CampeonatosNuevoRoute
  '/equinos/$id': typeof EquinosIdRouteWithChildren
  '/equinos/nuevo': typeof EquinosNuevoRoute
  '/participaciones/$id': typeof ParticipacionesIdRoute
  '/usuarios/nuevo': typeof UsuariosNuevoRoute
  '/campeonatos/': typeof CampeonatosIndexRoute
  '/equinos/': typeof EquinosIndexRoute
  '/campeonatos/$id/editar': typeof CampeonatosIdEditarRoute
  '/equinos/$id/editar': typeof EquinosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reportes': typeof ReportesRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/nuevo': typeof CampeonatosNuevoRoute
  '/equinos/$id': typeof EquinosIdRouteWithChildren
  '/equinos/nuevo': typeof EquinosNuevoRoute
  '/participaciones/$id': typeof ParticipacionesIdRoute
  '/usuarios/nuevo': typeof UsuariosNuevoRoute
  '/campeonatos': typeof CampeonatosIndexRoute
  '/equinos': typeof EquinosIndexRoute
  '/campeonatos/$id/editar': typeof CampeonatosIdEditarRoute
  '/equinos/$id/editar': typeof EquinosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reportes': typeof ReportesRoute
  '/campeonatos/$id': typeof CampeonatosIdRouteWithChildren
  '/campeonatos/nuevo': typeof CampeonatosNuevoRoute
  '/equinos/$id': typeof EquinosIdRouteWithChildren
  '/equinos/nuevo': typeof EquinosNuevoRoute
  '/participaciones/$id': typeof ParticipacionesIdRoute
  '/usuarios/nuevo': typeof UsuariosNuevoRoute
  '/campeonatos/': typeof CampeonatosIndexRoute
  '/equinos/': typeof EquinosIndexRoute
  '/campeonatos/$id/editar': typeof CampeonatosIdEditarRoute
  '/equinos/$id/editar': typeof EquinosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/health'
    | '/login'
    | '/reportes'
    | '/campeonatos/$id'
    | '/campeonatos/nuevo'
    | '/equinos/$id'
    | '/equinos/nuevo'
    | '/participaciones/$id'
    | '/usuarios/nuevo'
    | '/campeonatos/'
    | '/equinos/'
    | '/campeonatos/$id/editar'
    | '/equinos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/health'
    | '/login'
    | '/reportes'
    | '/campeonatos/$id'
    | '/campeonatos/nuevo'
    | '/equinos/$id'
    | '/equinos/nuevo'
    | '/participaciones/$id'
    | '/usuarios/nuevo'
    | '/campeonatos'
    | '/equinos'
    | '/campeonatos/$id/editar'
    | '/equinos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/health'
    | '/login'
    | '/reportes'
    | '/campeonatos/$id'
    | '/campeonatos/nuevo'
    | '/equinos/$id'
    | '/equinos/nuevo'
    | '/participaciones/$id'
    | '/usuarios/nuevo'
    | '/campeonatos/'
    | '/equinos/'
    | '/campeonatos/$id/editar'
    | '/equinos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ReportesRoute: typeof ReportesRoute
  CampeonatosIdRoute: typeof CampeonatosIdRouteWithChildren
  CampeonatosNuevoRoute: typeof CampeonatosNuevoRoute
  EquinosIdRoute: typeof EquinosIdRouteWithChildren
  EquinosNuevoRoute: typeof EquinosNuevoRoute
  ParticipacionesIdRoute: typeof ParticipacionesIdRoute
  UsuariosNuevoRoute: typeof UsuariosNuevoRoute
  CampeonatosIndexRoute: typeof CampeonatosIndexRoute
  EquinosIndexRoute: typeof EquinosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equinos/': {
      id: '/equinos/'
      path: '/equinos'
      fullPath: '/equinos/'
      preLoaderRoute: typeof EquinosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/': {
      id: '/campeonatos/'
      path: '/campeonatos'
      fullPath: '/campeonatos/'
      preLoaderRoute: typeof CampeonatosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/nuevo': {
      id: '/usuarios/nuevo'
      path: '/usuarios/nuevo'
      fullPath: '/usuarios/nuevo'
      preLoaderRoute: typeof UsuariosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participaciones/$id': {
      id: '/participaciones/$id'
      path: '/participaciones/$id'
      fullPath: '/participaciones/$id'
      preLoaderRoute: typeof ParticipacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equinos/nuevo': {
      id: '/equinos/nuevo'
      path: '/equinos/nuevo'
      fullPath: '/equinos/nuevo'
      preLoaderRoute: typeof EquinosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equinos/$id': {
      id: '/equinos/$id'
      path: '/equinos/$id'
      fullPath: '/equinos/$id'
      preLoaderRoute: typeof EquinosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/nuevo': {
      id: '/campeonatos/nuevo'
      path: '/campeonatos/nuevo'
      fullPath: '/campeonatos/nuevo'
      preLoaderRoute: typeof CampeonatosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos/$id': {
      id: '/campeonatos/$id'
      path: '/campeonatos/$id'
      fullPath: '/campeonatos/$id'
      preLoaderRoute: typeof CampeonatosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equinos/$id/editar': {
      id: '/equinos/$id/editar'
      path: '/editar'
      fullPath: '/equinos/$id/editar'
      preLoaderRoute: typeof EquinosIdEditarRouteImport
      parentRoute: typeof EquinosIdRoute
    }
    '/campeonatos/$id/editar': {
      id: '/campeonatos/$id/editar'
      path: '/editar'
      fullPath: '/campeonatos/$id/editar'
      preLoaderRoute: typeof CampeonatosIdEditarRouteImport
      parentRoute: typeof CampeonatosIdRoute
    }
  }
}

interface CampeonatosIdRouteChildren {
  CampeonatosIdEditarRoute: typeof CampeonatosIdEditarRoute
}

const CampeonatosIdRouteChildren: CampeonatosIdRouteChildren = {
  CampeonatosIdEditarRoute: CampeonatosIdEditarRoute,
}

const CampeonatosIdRouteWithChildren = CampeonatosIdRoute._addFileChildren(
  CampeonatosIdRouteChildren,
)

interface EquinosIdRouteChildren {
  EquinosIdEditarRoute: typeof EquinosIdEditarRoute
}

const EquinosIdRouteChildren: EquinosIdRouteChildren = {
  EquinosIdEditarRoute: EquinosIdEditarRoute,
}

const EquinosIdRouteWithChildren = EquinosIdRoute._addFileChildren(
  EquinosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ReportesRoute: ReportesRoute,
  CampeonatosIdRoute: CampeonatosIdRouteWithChildren,
  CampeonatosNuevoRoute: CampeonatosNuevoRoute,
  EquinosIdRoute: EquinosIdRouteWithChildren,
  EquinosNuevoRoute: EquinosNuevoRoute,
  ParticipacionesIdRoute: ParticipacionesIdRoute,
  UsuariosNuevoRoute: UsuariosNuevoRoute,
  CampeonatosIndexRoute: CampeonatosIndexRoute,
  EquinosIndexRoute: EquinosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
